### ISSUE TITLE
Proposed schema changes

### ISSUE THREAD

**Issue by jpolka** [transpose-publishing/policies-database#20]
Here are some suggested changes/additions!

- Would it be possible to add some of the headers that are present in [schema.yml](https://github.com/transpose-publishing/policies-database/blob/master/policies/schema.yml) - for example, OPEN PEER REVIEW, to the YAML files themselves? Furthermore, condensing down some of the white space (ie, between data fields that share the same reference url) might reduce the need to scroll so much. Each dsc could then be started with the name of the variable for disambiguation 
- "Peer review policy url (valid url)" -> "**Open** peer review policy url (valid url)"
- Add url for preprint-citation
- In the later part of the files, preprint urls follow the data fields, but in the early part, they preceed them. Suggest standardizing these
- preprint url fields descriptions could be standardized as well
- would be good to add "unknown" to most fields to signify that this information can't be found. If users don't look for info, they can leave the field null. But if they do look and can't find, they could use unknown. The absence of public information is also important...

**Comment by dhimmel** [comment]
@jpolka can you make a pull request with your edits to the schema. Do not merge it, but once i have the commit I can take it from there. This will be the first time we are changing the schema after there are already some annotations. Here's the computational workflow I'm envisioning:

1. Update the blank template data structure for each policy with existing annotations
2. Apply the data fields taken from RoMEO

This means that any changes to to the RoMEO fields will get overwritten.

> would be good to add "unknown" to most fields to signify that this information can't be found

Sounds reasonable to me! `not specified` would be an alternative, although perhaps `unknown` is a bit more general?

> Would it be possible to add some of the headers that are present in schema.yml - for example, OPEN PEER REVIEW, to the YAML files themselves? Furthermore, condensing down some of the white space (ie, between data fields that share the same reference url) might reduce the need to scroll so much.

I will see what's possible here given the treacherous documentation and attitude of `ruamel.yaml`.

> Each dsc could then be started with the name of the variable for disambiguation

If you did this, then I we wouldn't have to worry about section headers, and I could easily remove the newlines (which took me a very long time to add, but if they are more damaging then helpful, we should remove).

**Comment by dhimmel** [comment]
@jpolka IIRC you also mentioned the idea of adding a general comments field somewhere?

**Comment by jpolka** [comment]
> If you did this, then I we wouldn't have to worry about section headers, and I could easily remove the newlines (which took me a very long time to add, but if they are more damaging then helpful, we should remove).

Can we use \n for new lines in descriptions?

**Comment by jpolka** [comment]
As per the discussion [on Gitter](https://gitter.im/transpose-publishing/Lobby) with @cameronblandford, it would be good to add the following changes:

(Please also suggest different tags for the field, @tonyR-H ?)
Can enum be used in a str inside a seq, @dhimmel ?


```yaml
field
  type: seq
  desc: "Field - add all that apply. Add a new line for each. Start each line with two spaces, a dash, and one space, like this: '  - ' (biology/chemistry/physics/computer science/medicine/math/social science/humanities)"
  sequence:
    - type: str
      enum: [the above] #Not sure this will work -  http://www.kuwata-lab.com/kwalify/ruby/users-guide.01.html#schema 

visible 
  type: str
  desc: "Used by moderators to determine whether record is shown in frontend (yes/no) - do not edit 
  enum: [yes, no]
```
